name: productivity
name: productivity_app_ui
description: A daily planner / habit / goal / activity tracker app.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true